-- Chief federated relay v3.1 durable receiver ledger. SOURCE ONLY: do not treat this file as an applied production migration.
create extension if not exists "pgcrypto";
create table if not exists public.federated_relay_source_cursors (source_member text not null, source_key_id text not null, last_sequence bigint not null default -1, last_message_id uuid, updated_at timestamptz not null default now(), primary key(source_member,source_key_id));
create table if not exists public.federated_relay_chain_cursors (chain_id uuid primary key, last_position bigint not null default -1, last_message_id uuid, last_successor_cookie text not null default 'Q4R:v3.1:genesis', source_member text, source_repository text, source_branch text, target_member text, target_repository text, target_branch text, updated_at timestamptz not null default now());
create table if not exists public.federated_relay_messages (message_id uuid primary key, semantic_fingerprint char(64) not null, delivery_fingerprint char(64) not null, receipt_id uuid not null unique, chain_id uuid not null, chain_position bigint not null check(chain_position>=0), relation_type text not null check(relation_type in('root','reply','revision','reconcile')), parent_message_id uuid references public.federated_relay_messages(message_id), logical_operation_id uuid not null, source_member text not null, source_repository text not null, source_branch text not null, source_head_sha char(40) not null, source_key_id text not null, source_sequence bigint not null check(source_sequence>=0), target_member text not null, target_repository text not null, target_branch text not null, target_head_sha char(40) not null, nonce uuid not null, reply_to_message_id uuid references public.federated_relay_messages(message_id), predecessor_proof_cookie text not null, successor_proof_cookie text not null, payload_sha256 char(64) not null, evidence_digest char(64) not null, accepted_key_state jsonb not null, status text not null default 'accepted' check(status in('accepted','superseded','revoked')), issued_at timestamptz not null, expires_at timestamptz not null, accepted_at timestamptz not null default now(), superseded_by_message_id uuid references public.federated_relay_messages(message_id), envelope jsonb not null, receipt jsonb not null, unique(source_member,source_key_id,source_sequence), unique(source_member,source_key_id,nonce), unique(chain_id,chain_position));
create table if not exists public.federated_relay_supersessions (predecessor_message_id uuid primary key references public.federated_relay_messages(message_id), successor_message_id uuid not null references public.federated_relay_messages(message_id), chain_id uuid not null, logical_operation_id uuid not null, created_at timestamptz not null default now(), check(predecessor_message_id<>successor_message_id));
alter table public.federated_relay_source_cursors enable row level security; alter table public.federated_relay_chain_cursors enable row level security; alter table public.federated_relay_messages enable row level security; alter table public.federated_relay_supersessions enable row level security;
revoke all on table public.federated_relay_source_cursors,public.federated_relay_chain_cursors,public.federated_relay_messages,public.federated_relay_supersessions from public,anon,authenticated,service_role;
grant select on table public.federated_relay_source_cursors,public.federated_relay_chain_cursors,public.federated_relay_messages,public.federated_relay_supersessions to service_role;
create or replace function public.federated_relay_accept_v31(p_contract text,p_message_id uuid,p_semantic_fingerprint char(64),p_delivery_fingerprint char(64),p_receipt_id uuid,p_chain_id uuid,p_chain_position bigint,p_relation_type text,p_parent_message_id uuid,p_logical_operation_id uuid,p_source_member text,p_source_repository text,p_source_branch text,p_source_head_sha char(40),p_source_key_id text,p_source_sequence bigint,p_target_member text,p_target_repository text,p_target_branch text,p_target_head_sha char(40),p_nonce uuid,p_reply_to_message_id uuid,p_predecessor_proof_cookie text,p_successor_proof_cookie text,p_payload_sha256 char(64),p_evidence_digest char(64),p_accepted_key_state jsonb,p_issued_at timestamptz,p_expires_at timestamptz,p_envelope jsonb,p_receipt jsonb,p_supersedes_message_ids uuid[])
returns table(outcome text,stored_receipt jsonb,current_state text,superseded_by_message_id uuid) language plpgsql security definer set search_path=pg_catalog as $function$
declare source_cursor public.federated_relay_source_cursors%rowtype; chain_cursor public.federated_relay_chain_cursors%rowtype; existing_record public.federated_relay_messages%rowtype; parent_record public.federated_relay_messages%rowtype; prior_record public.federated_relay_messages%rowtype; sid uuid; same_direction boolean; inverted_direction boolean;
begin
 if p_contract<>'juss/federated-agent-relay@v3.1' then raise exception 'relay_contract'; end if;
 if p_expires_at<=p_issued_at or p_expires_at-p_issued_at>interval '5 minutes' or p_expires_at<now() or p_issued_at>now()+interval '30 seconds' then raise exception 'relay_freshness'; end if;
 if p_relation_type not in('root','reply','revision','reconcile') then raise exception 'relay_relation_type'; end if;
 if (p_source_member='founder-control-room' and p_source_repository<>'jussray/founder-control-room') or (p_source_member='chief-ai-machine' and p_source_repository<>'jussray/chief-ai-machine') or (p_source_member='solcontinuity' and p_source_repository<>'jussray/solcontinuity') or (p_source_member='promptos' and p_source_repository<>'jussray/promptos') then raise exception 'relay_source_repository'; end if;
 if (p_target_member='founder-control-room' and p_target_repository<>'jussray/founder-control-room') or (p_target_member='chief-ai-machine' and p_target_repository<>'jussray/chief-ai-machine') or (p_target_member='solcontinuity' and p_target_repository<>'jussray/solcontinuity') or (p_target_member='promptos' and p_target_repository<>'jussray/promptos') then raise exception 'relay_target_repository'; end if;
 select * into existing_record from public.federated_relay_messages where message_id=p_message_id; if found then if existing_record.semantic_fingerprint=p_semantic_fingerprint and existing_record.delivery_fingerprint=p_delivery_fingerprint then return query select 'duplicate',existing_record.receipt,existing_record.status,existing_record.superseded_by_message_id; return; end if; raise exception 'relay_message_id_collision'; end if;
 insert into public.federated_relay_source_cursors(source_member,source_key_id,last_sequence) values(p_source_member,p_source_key_id,-1) on conflict do nothing;
 select * into source_cursor from public.federated_relay_source_cursors where source_member=p_source_member and source_key_id=p_source_key_id for update;
 insert into public.federated_relay_chain_cursors(chain_id,last_position,last_successor_cookie) values(p_chain_id,-1,'Q4R:v3.1:genesis') on conflict do nothing;
 select * into chain_cursor from public.federated_relay_chain_cursors where chain_id=p_chain_id for update;
 select * into existing_record from public.federated_relay_messages where message_id=p_message_id; if found then if existing_record.semantic_fingerprint=p_semantic_fingerprint and existing_record.delivery_fingerprint=p_delivery_fingerprint then return query select 'duplicate',existing_record.receipt,existing_record.status,existing_record.superseded_by_message_id; return; end if; raise exception 'relay_message_id_collision'; end if;
 if p_source_sequence<>source_cursor.last_sequence+1 then raise exception 'relay_source_sequence_not_next'; end if; if p_chain_position<>chain_cursor.last_position+1 then raise exception 'relay_chain_position_not_next'; end if;
 if chain_cursor.last_position=-1 then
  if p_relation_type<>'root' or p_chain_position<>0 or p_parent_message_id is not null or p_reply_to_message_id is not null or p_predecessor_proof_cookie<>'Q4R:v3.1:genesis' then raise exception 'relay_root_invalid'; end if;
  update public.federated_relay_chain_cursors set source_member=p_source_member,source_repository=p_source_repository,source_branch=p_source_branch,target_member=p_target_member,target_repository=p_target_repository,target_branch=p_target_branch where chain_id=p_chain_id;
 else
  if p_relation_type='root' or p_parent_message_id<>chain_cursor.last_message_id or p_predecessor_proof_cookie<>chain_cursor.last_successor_cookie then raise exception 'relay_lineage'; end if;
  same_direction:=p_source_member=chain_cursor.source_member and p_source_repository=chain_cursor.source_repository and p_source_branch=chain_cursor.source_branch and p_target_member=chain_cursor.target_member and p_target_repository=chain_cursor.target_repository and p_target_branch=chain_cursor.target_branch;
  inverted_direction:=p_source_member=chain_cursor.target_member and p_source_repository=chain_cursor.target_repository and p_source_branch=chain_cursor.target_branch and p_target_member=chain_cursor.source_member and p_target_repository=chain_cursor.source_repository and p_target_branch=chain_cursor.source_branch;
  if not(same_direction or inverted_direction) then raise exception 'relay_chain_participant_pair_changed'; end if;
  select * into parent_record from public.federated_relay_messages where message_id=p_parent_message_id for update;
  if not found or parent_record.status<>'accepted' or parent_record.chain_id<>p_chain_id or parent_record.chain_position<>chain_cursor.last_position or parent_record.logical_operation_id<>p_logical_operation_id then raise exception 'relay_parent_invalid'; end if;
  if p_relation_type<>'reconcile' and parent_record.expires_at<now() then raise exception 'relay_parent_expired_requires_reconcile'; end if;
  if p_relation_type='reply' and not(p_source_member=parent_record.target_member and p_target_member=parent_record.source_member and p_reply_to_message_id=parent_record.message_id) then raise exception 'relay_reply_identity'; end if;
 end if;
 if p_relation_type='revision' and coalesce(array_length(p_supersedes_message_ids,1),0)=0 then raise exception 'relay_revision_without_supersession'; end if; if p_relation_type<>'revision' and coalesce(array_length(p_supersedes_message_ids,1),0)>0 then raise exception 'relay_supersession_requires_revision'; end if;
 if p_relation_type='revision' then foreach sid in array p_supersedes_message_ids loop select * into prior_record from public.federated_relay_messages where message_id=sid for update; if not found or prior_record.status<>'accepted' or prior_record.chain_id<>p_chain_id or prior_record.logical_operation_id<>p_logical_operation_id or prior_record.chain_position>=p_chain_position then raise exception 'relay_supersession_invalid'; end if; if exists(select 1 from public.federated_relay_supersessions where predecessor_message_id=sid) then raise exception 'relay_supersession_fork'; end if; end loop; end if;
 insert into public.federated_relay_messages(message_id,semantic_fingerprint,delivery_fingerprint,receipt_id,chain_id,chain_position,relation_type,parent_message_id,logical_operation_id,source_member,source_repository,source_branch,source_head_sha,source_key_id,source_sequence,target_member,target_repository,target_branch,target_head_sha,nonce,reply_to_message_id,predecessor_proof_cookie,successor_proof_cookie,payload_sha256,evidence_digest,accepted_key_state,issued_at,expires_at,envelope,receipt) values(p_message_id,p_semantic_fingerprint,p_delivery_fingerprint,p_receipt_id,p_chain_id,p_chain_position,p_relation_type,p_parent_message_id,p_logical_operation_id,p_source_member,p_source_repository,p_source_branch,p_source_head_sha,p_source_key_id,p_source_sequence,p_target_member,p_target_repository,p_target_branch,p_target_head_sha,p_nonce,p_reply_to_message_id,p_predecessor_proof_cookie,p_successor_proof_cookie,p_payload_sha256,p_evidence_digest,p_accepted_key_state,p_issued_at,p_expires_at,p_envelope,p_receipt);
 if p_relation_type='revision' then foreach sid in array p_supersedes_message_ids loop insert into public.federated_relay_supersessions values(sid,p_message_id,p_chain_id,p_logical_operation_id,now()); update public.federated_relay_messages set status='superseded',superseded_by_message_id=p_message_id where message_id=sid; end loop; end if;
 update public.federated_relay_source_cursors set last_sequence=p_source_sequence,last_message_id=p_message_id,updated_at=now() where source_member=p_source_member and source_key_id=p_source_key_id;
 update public.federated_relay_chain_cursors set last_position=p_chain_position,last_message_id=p_message_id,last_successor_cookie=p_successor_proof_cookie,updated_at=now() where chain_id=p_chain_id;
 return query select 'accepted',p_receipt,'accepted',null::uuid;
end $function$;
revoke all on function public.federated_relay_accept_v31(text,uuid,character,character,uuid,uuid,bigint,text,uuid,uuid,text,text,text,character,text,bigint,text,text,text,character,uuid,uuid,text,text,character,character,jsonb,timestamptz,timestamptz,jsonb,jsonb,uuid[]) from public,anon,authenticated; grant execute on function public.federated_relay_accept_v31(text,uuid,character,character,uuid,uuid,bigint,text,uuid,uuid,text,text,text,character,text,bigint,text,text,text,character,uuid,uuid,text,text,character,character,jsonb,timestamptz,timestamptz,jsonb,jsonb,uuid[]) to service_role;
